### PR TITLE
Add high-level description field and save path for tables

### PR DESCRIPTION
**Pull request by fpavogt**
Hey @gilleslandais, 

Thanks for the great package !

I'm going to use it for my first upload to VizieR, and while toying around I made the following tweaks which I thought may be of general interest:
- I added a general "Description" field, to match the VizieR example file (https://cdsarc.cds.unistra.fr/ftp/cats/J/A+A/382/389/ReadMe).
- I added a new `path` keyword to allow to specify where the tables should be save.

Feel free to close this PR if it is out-of-bounds. I've kept the changes at the bare minimum, but still added a `.gitignore` to make my life easier.

### CODE REVIEW

**Comment by gilleslandais** [comment]
Hello -
Thank you for your proposal.

for typo - thank you !
The ReadMe "Description" completes Abstract with information like objects of interest or resources used for data acquisition (telescop, filters, etc). It's sounds good, but  I would like also to avoid confusion between Abstract/Description. May be, it needs to adapt the template (to avoid empty Description) or to rename the parameter "description" (for instance "more_description" ?) .. Any idea?

About the path - I agree too that the filedescriptor (adapted for ReadMe creation) is may be not well adapted as table output.

**Comment by fpavogt** [comment]
Good point. I've added better descriptions (following the text written [here](https://vizier.cds.unistra.fr/vizier/submit.htx)) to both the default values and the Readme example. What do you think ?

**Comment by gilleslandais** [comment]
I prefer the last proposal (3029a03)  or may be:
"Optional description of the data context  (instrumentation used, observing conditions, etc...)."
and rename the attribute CDSTablesMaker.description --> CDSTablesMaker.more_description
I could rebuilt a nbew version from your proposal 


about the Path parameter  - table paths must be in phase with the "File Summary" section of ReadMe - in the same directory.
The current sate could be improved - I will see later - But I note your proposal.

**Comment by fpavogt** [comment]
Sounds good. I'll let you close this PR when you see fit, then. If for any reason you'd like to merge this, feel free to suggest specific changes via a formal review, and I'll implement them. 

Thanks for taking note of my suggestions !

**Comment by gilleslandais** [comment]
Ok - the new version is available in github  (not yet in Pypi)

**Pull request closed without merging**
